{
  imports = [
    ./android.nix
    ./bluetooth.nix
    ./boot.nix
    ./crypto.nix
    ./docker.nix
    ./fonts.nix
    #./framework.nix
    ./impermanence.nix
    ./mullvad.nix
    ./network.nix
    ./secrets.nix
    ./sway.nix
    ./system.nix
    ./thunar.nix
    ./users.nix
    ./wireless.nix
    ./zfs.nix
  ];
}
