keys:
  - &pholi 8BA973665D50A93C3B204E16E1834488946473D7 <-- todo change this, also can i move my age key to a custom place?
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *pholi
      