hello: ENC[AES256_GCM,data:nUwkHJaGsdiFSiUiggAmdr0hlZjhx8WoCXquhJzsXu4ekgYci3AvcjW3nm/K8g==,iv:8ytU8otjmt5FCsDYkdW5eRg5LEgkQoXowjOwmYgmZ7w=,tag:DldUgLVnH1tPyg//dwt+GQ==,type:str]
example_key: ENC[AES256_GCM,data:Fp723ClOUfbB3PQ8/A==,iv:++JovwuZuPMOFRjc9fQBcxMYF9LbcuZM8JI+T65ozNU=,tag:ELoQwnlW5svU979c8nvutQ==,type:str]
#ENC[AES256_GCM,data:5E1SAPCclI7r/Ai6tuzWAw==,iv:baXkt+vkOAJiOHrDx0eJDzXoOpez44I+YRx+tzYVHqo=,tag:RGO8JO88Ozdci9nrq6TuxQ==,type:comment]
example_array:
    - ENC[AES256_GCM,data:A8N6bdSxfxShJqZJ/i4J,iv:8K7q8wh/lS1XfSCix0y2EW2D3DSGd2co8UC+afBbW0E=,tag:rohfGpAIA6XRIsgK3wrNIg==,type:str]
    - ENC[AES256_GCM,data:LHYOfawu0bJxho7WMp8=,iv:9cWtODK6BQd68Yknw0yLeSS1zykDG8Oaogu4u+GjG8w=,tag:yH7Y1r7LPZGlMjRx/D++Tg==,type:str]
mystring: ENC[AES256_GCM,data:zXAVvo4=,iv:vhIh/mWkjf7XxRhztnBRw5xZOTe+xvkOjTYJOc51MGs=,tag:7V3tnqYAQIvxhb93ZpiWEg==,type:str]
example_number: ENC[AES256_GCM,data:C5S6JNTDSOxokA==,iv:EXnt8GV6r8SComkC/4m1bwpu8R4NrEGj/OlUUdB4OPo=,tag:wizcj5aq+edc1tCz4/NELA==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:d++Hdw==,iv:J2LE6aIf4APdeopMlCtKG9MRSc1MB3BIVP/X4zZEVUU=,tag:6sstSgpQ92Ho26LB0uATrw==,type:bool]
    - ENC[AES256_GCM,data:snVTmXY=,iv:N21upOTluLnp2Qa/XCBzpRlxxClyPLVmn5mXwH33SlA=,tag:qMTNulrV7BQ0wjEak33rEA==,type:bool]
wireless.env:
    - ENC[AES256_GCM,data:FTO6LPkmgSE5881WhaZn1RSl6DcuimDV4g==,iv:H2ifEknMfK2iawFs4N1CR1aVJTsRKWJ+K/Q4yszmbCE=,tag:cbjZr/0H4uyDQ6imWtznSw==,type:str]
    - ENC[AES256_GCM,data:8Vm9pUE3Gnky/7sk98N1g24FbrT07LJtlMBHA8YwSu1/DzI=,iv:gN1Kd0ApkQn/1Nx0Kjx9zY4lqZnN6NeNHwLGF2ClXzo=,tag:L2YKG6DqvHF2Y5B407tMJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-08T13:07:35Z"
    mac: ENC[AES256_GCM,data:kH9T2pT+u/7elvDTrGQgR3wZ/4MBwZ49jQVE3y9E4OoAIjHTX2r2MaOkvcqjCb0qlYpobFrdq+tRCO6dpmzwuaLELSe/J21R17asyp+DMsq1ru+de3wWrWIYNHMMPkEENY3bDEQerWJbDmSjkyRI+0W3L66i1RkQPoKl5v5vHH0=,iv:zDq1HnqGIyHB+xa44AA4rNzKyhIG8lUSRj0H3iOFV9w=,tag:8suAEiFhLujPGyO74LIg7A==,type:str]
    pgp:
        - created_at: "2024-07-06T16:32:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYSTc+ElmwfUSAQdAfnH+5Vr/vkWQ2s79vU4jsLZewGJQYEs3/mc7DaF8Zzcw
            RRHPPU/NusFUn3mRW7tY6ZCeyuk8PTlkqjIe0zzEmNI2UEr78is1MK3HtXefzZp0
            1GYBCQIQRs1EKpFTBI2wb+OklxTrooXEKSKfz0FKcSXSQ2uFLCuSIZ7qMx6rlf2r
            6P7hTUCHLCkrbj6VpdCG3820Oc7EzBd+L8Uok1fHVXrGvl0IIFsC+ZOwHKAREGOK
            kxarlCmZBCc=
            =2S5R
            -----END PGP MESSAGE-----
          fp: 9C1F8231BB5A1EFC6CBCD48C721454EB12B2B854
    unencrypted_suffix: _unencrypted
    version: 3.8.1
